# Generated by Django 3.1.3 on 2022-08-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20200813_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=110)),
                ('nombre', models.TextField(max_length=250)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('Fecha_compra', models.DateField()),
                ('Fecha_registro', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
